"""Dogfood samples: docloom explaining docloom.

Every file in this folder was generated by docloom's OWN pipeline from the
project's `PROJECT.md` — a reliable model authored the validated IR, and these
deterministic renderers produced the files in `output/`. This is the actual
output the system generates, not a hand-tuned mock-up.

Run from the repo root:

    python examples/dogfood/render_samples.py  ->  examples/dogfood/output/*

The architecture diagrams use the two layout backends: `architecture.json` (a
clean linear pipeline) via the default solver, and `architecture-full.json` (the
full branching architecture) via the optional Graphviz-`dot` backend
(`pip install "docloom[dotlayout]"`), which lays complex graphs out compactly.
"""
import json
from pathlib import Path

from docloom import Document, Theme, render, render_diagram
from docloom.ir import Diagram

HERE = Path(__file__).parent
OUT = HERE / "output"
OUT.mkdir(exist_ok=True)

# The studio's "aurora" theme, inlined so this example is self-contained.
AURORA = Theme(
    primary="#1F3D63", accent="#2F62A0", background="#F7F8FA", surface="#EBEEF3",
    text="#14161A", muted="#5E6B7A",
    font_heading="IBM Plex Sans", font_body="IBM Plex Sans",
)


def _load(name: str) -> dict:
    return json.loads((HERE / name).read_text(encoding="utf-8"))


def main() -> None:
    # Documents (deck / report / infographic / workbook)
    jobs = [
        ("deck.json", "deck", ["pptx", "pdf"]),
        ("whitepaper.json", "whitepaper", ["pdf", "docx", "html", "md"]),
        ("infographic.json", "infographic", ["pptx", "pdf"]),
        ("workbook.json", "workbook", ["xlsx"]),
    ]
    for src, stem, fmts in jobs:
        doc = Document.model_validate(_load(src))
        for fmt in fmts:
            ext = "typ" if fmt == "typ" else fmt
            render(doc, fmt, OUT / f"{stem}.{ext}", AURORA)
        print(f"{stem}: {', '.join(fmts)}")

    # Architecture diagrams: SVG + PNG + editable .drawio. Each renders with the
    # layout backend its own IR declares (Diagram.layout) -- the full branching
    # architecture uses "dot" (Graphviz, compact group boxes; needs the
    # [dotlayout] extra, falls back to native if absent).
    for src, stem in [("architecture.json", "architecture"),
                      ("architecture-full.json", "architecture-full")]:
        d = Diagram.model_validate(_load(src))
        for fmt in ("svg", "png", "drawio"):
            data = render_diagram(d, AURORA, fmt)  # honors d.layout
            path = OUT / f"{stem}.{fmt}"
            mode = "wb" if isinstance(data, bytes) else "w"
            with open(path, mode, **({} if mode == "wb" else {"encoding": "utf-8"})) as f:
                f.write(data)
        print(f"{stem} diagram ({d.layout} layout): svg, png, drawio")


if __name__ == "__main__":
    main()
